apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: webapp
type: Opaque
data:
  POSTGRES_PASSWORD: <à encoder en base64>
  POSTGRES_USER: <à encoder en base64>
  POSTGRES_DB: <à encoder en base64>
